version: "3"
services:
  metatrader_service:
    container_name: metatrader
    image: ejtrader/metatrader:5
    restart: unless-stopped
    ports:
      - "5900:5900"
      - "15555:15555"
      - "15556:15556"
      - "15557:15557"
      - "15558:15558"
    volumes:
      - ejtraderMT:/data
    environment:
      - DISPLAY=host.docker.internal:0
      - MT5_PASSWORD=your_password
      - MT5_SERVER=your_server

  trading_bot:
    container_name: trading_bot
    build:
      context: .
      dockerfile: docker/DockerFile
    volumes:
      - ./app:/app
    depends_on:
      - metatrader_service

  mt5_bridge:
    container_name: mt5_bridge
    build:
      context: .
      dockerfile: docker/DockerFile.mt5_bridge
    volumes:
      - ./bridge:/bridge
    depends_on:
      - metatrader_service
      - trading_bot

volumes:
  ejtraderMT: {}
