version: "3"
services:
  metatrader_service:
    image: ejtrader/metatrader:5
    container_name: metatrader
    restart: unless-stopped
    environment:
      - DISPLAY=$DISPLAY
    privileged: true
    volumes:
      - ejtraderMT:/data
    ports:
      - "5900:5900"
      - "15555:15555"
      - "15556:15556"
      - "15557:15557"
      - "15558:15558"
    networks:
      - trading_network

  trading_bot:
    container_name: trading_bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/DockerFile
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    depends_on:
      - metatrader_service
    networks:
      - trading_network

  mt5_bridge:
    container_name: mt5_bridge
    build:
      context: .
      dockerfile: docker/DockerFile.mt5_bridge
    volumes:
      - ./bridge:/bridge
    depends_on:
      - metatrader_service
      - trading_bot
    networks:
      - trading_network

networks:
  trading_network:
    driver: bridge

volumes:
  ejtraderMT: {}
