FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the bridge script to the container
COPY bridge/mt5_bridge.py .

# Install any dependencies required by the bridge script
RUN pip install python-socketio python-engineio

CMD ["python", "mt5_bridge.py"]
